update fastlane and disstribution for android

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -15,26 +15,27 @@ workflows:
         - name: Set Android SDK location
           script: | 
             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+        - name: Set up fastlane, notification, increase build number
+          script: |
+            sudo gem install fastlane
+            gem install bundler
+            bundle install
+            fastlane start_build_telegram
+            cd ..
+            fastlane increase_build_number_android env:develop
         - name: Build Android release
           script: | 
-            yarn android:develop
+            # LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+            # if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+            #   # fallback in case no build number was found from Google Play.
+            #   # Alternatively, you can `exit 1` to fail the build
+            #   # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+            #   # of times this workflow has been built
+            #     UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            # else
+            #     UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+            # fi
             cd android
             ./gradlew assembleDevelopRelease
-        - name: Build Android release
-          script: | 
-            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-              # fallback in case no build number was found from Google Play.
-              # Alternatively, you can `exit 1` to fail the build
-              # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-              # of times this workflow has been built
-                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-            else
-                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-            fi
-            cd android
-            ./gradlew bundleRelease \
-                -PversionCode=$UPDATED_BUILD_NUMBER \
-                -PversionName=1.0.$UPDATED_BUILD_NUMBER
             artifacts:
                 - android/app/build/outputs/**/*.aab
